
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AC = 17;
  public static final int MULT = 23;
  public static final int CONST = 36;
  public static final int SOMA = 21;
  public static final int MENORQ = 29;
  public static final int MAIORQ = 28;
  public static final int ATT = 25;
  public static final int PRIVATE = 12;
  public static final int MENORI = 31;
  public static final int INT = 7;
  public static final int ARRAY = 20;
  public static final int ERRO = 38;
  public static final int MAIORI = 30;
  public static final int VIRGULA = 19;
  public static final int E = 33;
  public static final int IGUAL = 26;
  public static final int FP = 16;
  public static final int OU = 34;
  public static final int BOOL = 9;
  public static final int DIV = 24;
  public static final int IF = 3;
  public static final int FC = 18;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int DIF = 27;
  public static final int VOID = 10;
  public static final int PROTECTED = 13;
  public static final int WS = 37;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 11;
  public static final int STRING = 8;
  public static final int FALSE = 6;
  public static final int NAO = 32;
  public static final int AP = 15;
  public static final int SUB = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "IF",
  "TRUE",
  "FLOAT",
  "FALSE",
  "INT",
  "STRING",
  "BOOL",
  "VOID",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "RETURN",
  "AP",
  "FP",
  "AC",
  "FC",
  "VIRGULA",
  "ARRAY",
  "SOMA",
  "SUB",
  "MULT",
  "DIV",
  "ATT",
  "IGUAL",
  "DIF",
  "MAIORQ",
  "MENORQ",
  "MAIORI",
  "MENORI",
  "NAO",
  "E",
  "OU",
  "ID",
  "CONST",
  "WS",
  "ERRO"
  };
}

