
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AC = 18;
  public static final int MULT = 27;
  public static final int CONST = 40;
  public static final int SOMA = 25;
  public static final int STR = 9;
  public static final int MENORQ = 33;
  public static final int MAIORQ = 32;
  public static final int ATT = 29;
  public static final int PRIVATE = 13;
  public static final int MENORI = 35;
  public static final int FLT = 6;
  public static final int INT = 7;
  public static final int ARRAY = 24;
  public static final int ERRO = 42;
  public static final int MAIORI = 34;
  public static final int VIRGULA = 23;
  public static final int PONTO = 22;
  public static final int E = 37;
  public static final int FLUT = 41;
  public static final int IGUAL = 30;
  public static final int FP = 17;
  public static final int OU = 38;
  public static final int DIV = 28;
  public static final int IF = 3;
  public static final int FC = 19;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int PONTO_VIRGULA = 21;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int ASP = 20;
  public static final int DIF = 31;
  public static final int VOID = 11;
  public static final int PROTECTED = 14;
  public static final int WS = 43;
  public static final int BOL = 8;
  public static final int PUBLIC = 12;
  public static final int STRING = 10;
  public static final int FALSE = 5;
  public static final int NAO = 36;
  public static final int AP = 16;
  public static final int SUB = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "IF",
  "TRUE",
  "FALSE",
  "FLT",
  "INT",
  "BOL",
  "STR",
  "STRING",
  "VOID",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "RETURN",
  "AP",
  "FP",
  "AC",
  "FC",
  "ASP",
  "PONTO_VIRGULA",
  "PONTO",
  "VIRGULA",
  "ARRAY",
  "SOMA",
  "SUB",
  "MULT",
  "DIV",
  "ATT",
  "IGUAL",
  "DIF",
  "MAIORQ",
  "MENORQ",
  "MAIORI",
  "MENORI",
  "NAO",
  "E",
  "OU",
  "ID",
  "CONST",
  "FLUT",
  "ERRO",
  "WS"
  };
}

